// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocking

import (
	"adora-test/internal/service"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewCarrier creates a new instance of Carrier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCarrier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Carrier {
	mock := &Carrier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Carrier is an autogenerated mock type for the Carrier type
type Carrier struct {
	mock.Mock
}

type Carrier_Expecter struct {
	mock *mock.Mock
}

func (_m *Carrier) EXPECT() *Carrier_Expecter {
	return &Carrier_Expecter{mock: &_m.Mock}
}

// GetStatus provides a mock function for the type Carrier
func (_mock *Carrier) GetStatus(ctx context.Context, userID string) (*service.CarrierStatus, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 *service.CarrierStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*service.CarrierStatus, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *service.CarrierStatus); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CarrierStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Carrier_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type Carrier_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Carrier_Expecter) GetStatus(ctx interface{}, userID interface{}) *Carrier_GetStatus_Call {
	return &Carrier_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx, userID)}
}

func (_c *Carrier_GetStatus_Call) Run(run func(ctx context.Context, userID string)) *Carrier_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Carrier_GetStatus_Call) Return(carrierStatus *service.CarrierStatus, err error) *Carrier_GetStatus_Call {
	_c.Call.Return(carrierStatus, err)
	return _c
}

func (_c *Carrier_GetStatus_Call) RunAndReturn(run func(ctx context.Context, userID string) (*service.CarrierStatus, error)) *Carrier_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}
