// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocking

import (
	"adora-test/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewEntitlementRepository creates a new instance of EntitlementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntitlementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntitlementRepository {
	mock := &EntitlementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EntitlementRepository is an autogenerated mock type for the EntitlementRepository type
type EntitlementRepository struct {
	mock.Mock
}

type EntitlementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *EntitlementRepository) EXPECT() *EntitlementRepository_Expecter {
	return &EntitlementRepository_Expecter{mock: &_m.Mock}
}

// FindByUserID provides a mock function for the type EntitlementRepository
func (_mock *EntitlementRepository) FindByUserID(ctx context.Context, userID string) (*domain.Entitlement, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 *domain.Entitlement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Entitlement, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Entitlement); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Entitlement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntitlementRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type EntitlementRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *EntitlementRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *EntitlementRepository_FindByUserID_Call {
	return &EntitlementRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *EntitlementRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *EntitlementRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntitlementRepository_FindByUserID_Call) Return(entitlement *domain.Entitlement, err error) *EntitlementRepository_FindByUserID_Call {
	_c.Call.Return(entitlement, err)
	return _c
}

func (_c *EntitlementRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*domain.Entitlement, error)) *EntitlementRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type EntitlementRepository
func (_mock *EntitlementRepository) Insert(ctx context.Context, entitlement *domain.Entitlement) error {
	ret := _mock.Called(ctx, entitlement)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Entitlement) error); ok {
		r0 = returnFunc(ctx, entitlement)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EntitlementRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type EntitlementRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - entitlement *domain.Entitlement
func (_e *EntitlementRepository_Expecter) Insert(ctx interface{}, entitlement interface{}) *EntitlementRepository_Insert_Call {
	return &EntitlementRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, entitlement)}
}

func (_c *EntitlementRepository_Insert_Call) Run(run func(ctx context.Context, entitlement *domain.Entitlement)) *EntitlementRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Entitlement
		if args[1] != nil {
			arg1 = args[1].(*domain.Entitlement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntitlementRepository_Insert_Call) Return(err error) *EntitlementRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EntitlementRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, entitlement *domain.Entitlement) error) *EntitlementRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type EntitlementRepository
func (_mock *EntitlementRepository) Update(ctx context.Context, entitlement *domain.Entitlement) error {
	ret := _mock.Called(ctx, entitlement)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Entitlement) error); ok {
		r0 = returnFunc(ctx, entitlement)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EntitlementRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type EntitlementRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - entitlement *domain.Entitlement
func (_e *EntitlementRepository_Expecter) Update(ctx interface{}, entitlement interface{}) *EntitlementRepository_Update_Call {
	return &EntitlementRepository_Update_Call{Call: _e.mock.On("Update", ctx, entitlement)}
}

func (_c *EntitlementRepository_Update_Call) Run(run func(ctx context.Context, entitlement *domain.Entitlement)) *EntitlementRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Entitlement
		if args[1] != nil {
			arg1 = args[1].(*domain.Entitlement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntitlementRepository_Update_Call) Return(err error) *EntitlementRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EntitlementRepository_Update_Call) RunAndReturn(run func(ctx context.Context, entitlement *domain.Entitlement) error) *EntitlementRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
