// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocking

import (
	"adora-test/internal/domain"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

type NotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationRepository) EXPECT() *NotificationRepository_Expecter {
	return &NotificationRepository_Expecter{mock: &_m.Mock}
}

// FindDue provides a mock function for the type NotificationRepository
func (_mock *NotificationRepository) FindDue(ctx context.Context, now time.Time) ([]*domain.Notification, error) {
	ret := _mock.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for FindDue")
	}

	var r0 []*domain.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) ([]*domain.Notification, error)); ok {
		return returnFunc(ctx, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) []*domain.Notification); ok {
		r0 = returnFunc(ctx, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationRepository_FindDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDue'
type NotificationRepository_FindDue_Call struct {
	*mock.Call
}

// FindDue is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *NotificationRepository_Expecter) FindDue(ctx interface{}, now interface{}) *NotificationRepository_FindDue_Call {
	return &NotificationRepository_FindDue_Call{Call: _e.mock.On("FindDue", ctx, now)}
}

func (_c *NotificationRepository_FindDue_Call) Run(run func(ctx context.Context, now time.Time)) *NotificationRepository_FindDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationRepository_FindDue_Call) Return(notifications []*domain.Notification, err error) *NotificationRepository_FindDue_Call {
	_c.Call.Return(notifications, err)
	return _c
}

func (_c *NotificationRepository_FindDue_Call) RunAndReturn(run func(ctx context.Context, now time.Time) ([]*domain.Notification, error)) *NotificationRepository_FindDue_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type NotificationRepository
func (_mock *NotificationRepository) Insert(ctx context.Context, notification *domain.Notification) error {
	ret := _mock.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Notification) error); ok {
		r0 = returnFunc(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NotificationRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type NotificationRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - notification *domain.Notification
func (_e *NotificationRepository_Expecter) Insert(ctx interface{}, notification interface{}) *NotificationRepository_Insert_Call {
	return &NotificationRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, notification)}
}

func (_c *NotificationRepository_Insert_Call) Run(run func(ctx context.Context, notification *domain.Notification)) *NotificationRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Notification
		if args[1] != nil {
			arg1 = args[1].(*domain.Notification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationRepository_Insert_Call) Return(err error) *NotificationRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NotificationRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, notification *domain.Notification) error) *NotificationRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type NotificationRepository
func (_mock *NotificationRepository) Update(ctx context.Context, notification *domain.Notification) error {
	ret := _mock.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Notification) error); ok {
		r0 = returnFunc(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NotificationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type NotificationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - notification *domain.Notification
func (_e *NotificationRepository_Expecter) Update(ctx interface{}, notification interface{}) *NotificationRepository_Update_Call {
	return &NotificationRepository_Update_Call{Call: _e.mock.On("Update", ctx, notification)}
}

func (_c *NotificationRepository_Update_Call) Run(run func(ctx context.Context, notification *domain.Notification)) *NotificationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Notification
		if args[1] != nil {
			arg1 = args[1].(*domain.Notification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationRepository_Update_Call) Return(err error) *NotificationRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NotificationRepository_Update_Call) RunAndReturn(run func(ctx context.Context, notification *domain.Notification) error) *NotificationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
