// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocking

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewPoller creates a new instance of Poller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPoller(t interface {
	mock.TestingT
	Cleanup(func())
}) *Poller {
	mock := &Poller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Poller is an autogenerated mock type for the Poller type
type Poller struct {
	mock.Mock
}

type Poller_Expecter struct {
	mock *mock.Mock
}

func (_m *Poller) EXPECT() *Poller_Expecter {
	return &Poller_Expecter{mock: &_m.Mock}
}

// Poll provides a mock function for the type Poller
func (_mock *Poller) Poll(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Poll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Poller_Poll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Poll'
type Poller_Poll_Call struct {
	*mock.Call
}

// Poll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Poller_Expecter) Poll(ctx interface{}, userID interface{}) *Poller_Poll_Call {
	return &Poller_Poll_Call{Call: _e.mock.On("Poll", ctx, userID)}
}

func (_c *Poller_Poll_Call) Run(run func(ctx context.Context, userID string)) *Poller_Poll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Poller_Poll_Call) Return(err error) *Poller_Poll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Poller_Poll_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *Poller_Poll_Call {
	_c.Call.Return(run)
	return _c
}
