// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocking

import (
	"adora-test/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewStoreEventRepository creates a new instance of StoreEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreEventRepository {
	mock := &StoreEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StoreEventRepository is an autogenerated mock type for the StoreEventRepository type
type StoreEventRepository struct {
	mock.Mock
}

type StoreEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *StoreEventRepository) EXPECT() *StoreEventRepository_Expecter {
	return &StoreEventRepository_Expecter{mock: &_m.Mock}
}

// FindByEventID provides a mock function for the type StoreEventRepository
func (_mock *StoreEventRepository) FindByEventID(ctx context.Context, eventID string) (*domain.StoreEvent, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for FindByEventID")
	}

	var r0 *domain.StoreEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.StoreEvent, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.StoreEvent); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StoreEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreEventRepository_FindByEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEventID'
type StoreEventRepository_FindByEventID_Call struct {
	*mock.Call
}

// FindByEventID is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *StoreEventRepository_Expecter) FindByEventID(ctx interface{}, eventID interface{}) *StoreEventRepository_FindByEventID_Call {
	return &StoreEventRepository_FindByEventID_Call{Call: _e.mock.On("FindByEventID", ctx, eventID)}
}

func (_c *StoreEventRepository_FindByEventID_Call) Run(run func(ctx context.Context, eventID string)) *StoreEventRepository_FindByEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreEventRepository_FindByEventID_Call) Return(storeEvent *domain.StoreEvent, err error) *StoreEventRepository_FindByEventID_Call {
	_c.Call.Return(storeEvent, err)
	return _c
}

func (_c *StoreEventRepository_FindByEventID_Call) RunAndReturn(run func(ctx context.Context, eventID string) (*domain.StoreEvent, error)) *StoreEventRepository_FindByEventID_Call {
	_c.Call.Return(run)
	return _c
}

// FindLatestByUserID provides a mock function for the type StoreEventRepository
func (_mock *StoreEventRepository) FindLatestByUserID(ctx context.Context, userID string) (*domain.StoreEvent, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindLatestByUserID")
	}

	var r0 *domain.StoreEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.StoreEvent, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.StoreEvent); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StoreEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreEventRepository_FindLatestByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLatestByUserID'
type StoreEventRepository_FindLatestByUserID_Call struct {
	*mock.Call
}

// FindLatestByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *StoreEventRepository_Expecter) FindLatestByUserID(ctx interface{}, userID interface{}) *StoreEventRepository_FindLatestByUserID_Call {
	return &StoreEventRepository_FindLatestByUserID_Call{Call: _e.mock.On("FindLatestByUserID", ctx, userID)}
}

func (_c *StoreEventRepository_FindLatestByUserID_Call) Run(run func(ctx context.Context, userID string)) *StoreEventRepository_FindLatestByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreEventRepository_FindLatestByUserID_Call) Return(storeEvent *domain.StoreEvent, err error) *StoreEventRepository_FindLatestByUserID_Call {
	_c.Call.Return(storeEvent, err)
	return _c
}

func (_c *StoreEventRepository_FindLatestByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*domain.StoreEvent, error)) *StoreEventRepository_FindLatestByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type StoreEventRepository
func (_mock *StoreEventRepository) Insert(ctx context.Context, storeEvent *domain.StoreEvent) error {
	ret := _mock.Called(ctx, storeEvent)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.StoreEvent) error); ok {
		r0 = returnFunc(ctx, storeEvent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreEventRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type StoreEventRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - storeEvent *domain.StoreEvent
func (_e *StoreEventRepository_Expecter) Insert(ctx interface{}, storeEvent interface{}) *StoreEventRepository_Insert_Call {
	return &StoreEventRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, storeEvent)}
}

func (_c *StoreEventRepository_Insert_Call) Run(run func(ctx context.Context, storeEvent *domain.StoreEvent)) *StoreEventRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.StoreEvent
		if args[1] != nil {
			arg1 = args[1].(*domain.StoreEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StoreEventRepository_Insert_Call) Return(err error) *StoreEventRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreEventRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, storeEvent *domain.StoreEvent) error) *StoreEventRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}
