// Code generated by ent, DO NOT EDIT.

package storeevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the storeevent type in the database.
	Label = "store_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventID holds the string denoting the event_id field in the database.
	FieldEventID = "event_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldEventTimeMs holds the string denoting the event_time_ms field in the database.
	FieldEventTimeMs = "event_time_ms"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldReceivedAt holds the string denoting the received_at field in the database.
	FieldReceivedAt = "received_at"
	// Table holds the table name of the storeevent in the database.
	Table = "store_events"
)

// Columns holds all SQL columns for storeevent fields.
var Columns = []string{
	FieldID,
	FieldEventID,
	FieldUserID,
	FieldType,
	FieldEventTimeMs,
	FieldProductID,
	FieldReceivedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultReceivedAt holds the default value on creation for the "received_at" field.
	DefaultReceivedAt func() time.Time
)

// OrderOption defines the ordering options for the StoreEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventID orders the results by the event_id field.
func ByEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByEventTimeMs orders the results by the event_time_ms field.
func ByEventTimeMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventTimeMs, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByReceivedAt orders the results by the received_at field.
func ByReceivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceivedAt, opts...).ToFunc()
}
