// Code generated by ent, DO NOT EDIT.

package storeevent

import (
	"adora-test/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldLTE(FieldID, id))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEQ(FieldEventID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEQ(FieldUserID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEQ(FieldType, v))
}

// EventTimeMs applies equality check predicate on the "event_time_ms" field. It's identical to EventTimeMsEQ.
func EventTimeMs(v int64) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEQ(FieldEventTimeMs, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEQ(FieldProductID, v))
}

// ReceivedAt applies equality check predicate on the "received_at" field. It's identical to ReceivedAtEQ.
func ReceivedAt(v time.Time) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEQ(FieldReceivedAt, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldNotIn(FieldEventID, vs...))
}

// EventIDGT applies the GT predicate on the "event_id" field.
func EventIDGT(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldGT(FieldEventID, v))
}

// EventIDGTE applies the GTE predicate on the "event_id" field.
func EventIDGTE(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldGTE(FieldEventID, v))
}

// EventIDLT applies the LT predicate on the "event_id" field.
func EventIDLT(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldLT(FieldEventID, v))
}

// EventIDLTE applies the LTE predicate on the "event_id" field.
func EventIDLTE(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldLTE(FieldEventID, v))
}

// EventIDContains applies the Contains predicate on the "event_id" field.
func EventIDContains(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldContains(FieldEventID, v))
}

// EventIDHasPrefix applies the HasPrefix predicate on the "event_id" field.
func EventIDHasPrefix(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldHasPrefix(FieldEventID, v))
}

// EventIDHasSuffix applies the HasSuffix predicate on the "event_id" field.
func EventIDHasSuffix(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldHasSuffix(FieldEventID, v))
}

// EventIDEqualFold applies the EqualFold predicate on the "event_id" field.
func EventIDEqualFold(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEqualFold(FieldEventID, v))
}

// EventIDContainsFold applies the ContainsFold predicate on the "event_id" field.
func EventIDContainsFold(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldContainsFold(FieldEventID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldContainsFold(FieldUserID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldContainsFold(FieldType, v))
}

// EventTimeMsEQ applies the EQ predicate on the "event_time_ms" field.
func EventTimeMsEQ(v int64) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEQ(FieldEventTimeMs, v))
}

// EventTimeMsNEQ applies the NEQ predicate on the "event_time_ms" field.
func EventTimeMsNEQ(v int64) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldNEQ(FieldEventTimeMs, v))
}

// EventTimeMsIn applies the In predicate on the "event_time_ms" field.
func EventTimeMsIn(vs ...int64) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldIn(FieldEventTimeMs, vs...))
}

// EventTimeMsNotIn applies the NotIn predicate on the "event_time_ms" field.
func EventTimeMsNotIn(vs ...int64) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldNotIn(FieldEventTimeMs, vs...))
}

// EventTimeMsGT applies the GT predicate on the "event_time_ms" field.
func EventTimeMsGT(v int64) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldGT(FieldEventTimeMs, v))
}

// EventTimeMsGTE applies the GTE predicate on the "event_time_ms" field.
func EventTimeMsGTE(v int64) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldGTE(FieldEventTimeMs, v))
}

// EventTimeMsLT applies the LT predicate on the "event_time_ms" field.
func EventTimeMsLT(v int64) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldLT(FieldEventTimeMs, v))
}

// EventTimeMsLTE applies the LTE predicate on the "event_time_ms" field.
func EventTimeMsLTE(v int64) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldLTE(FieldEventTimeMs, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldGT(FieldProductID, v))
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldGTE(FieldProductID, v))
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldLT(FieldProductID, v))
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldLTE(FieldProductID, v))
}

// ProductIDContains applies the Contains predicate on the "product_id" field.
func ProductIDContains(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldContains(FieldProductID, v))
}

// ProductIDHasPrefix applies the HasPrefix predicate on the "product_id" field.
func ProductIDHasPrefix(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldHasPrefix(FieldProductID, v))
}

// ProductIDHasSuffix applies the HasSuffix predicate on the "product_id" field.
func ProductIDHasSuffix(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldHasSuffix(FieldProductID, v))
}

// ProductIDEqualFold applies the EqualFold predicate on the "product_id" field.
func ProductIDEqualFold(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEqualFold(FieldProductID, v))
}

// ProductIDContainsFold applies the ContainsFold predicate on the "product_id" field.
func ProductIDContainsFold(v string) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldContainsFold(FieldProductID, v))
}

// ReceivedAtEQ applies the EQ predicate on the "received_at" field.
func ReceivedAtEQ(v time.Time) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldEQ(FieldReceivedAt, v))
}

// ReceivedAtNEQ applies the NEQ predicate on the "received_at" field.
func ReceivedAtNEQ(v time.Time) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldNEQ(FieldReceivedAt, v))
}

// ReceivedAtIn applies the In predicate on the "received_at" field.
func ReceivedAtIn(vs ...time.Time) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldIn(FieldReceivedAt, vs...))
}

// ReceivedAtNotIn applies the NotIn predicate on the "received_at" field.
func ReceivedAtNotIn(vs ...time.Time) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldNotIn(FieldReceivedAt, vs...))
}

// ReceivedAtGT applies the GT predicate on the "received_at" field.
func ReceivedAtGT(v time.Time) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldGT(FieldReceivedAt, v))
}

// ReceivedAtGTE applies the GTE predicate on the "received_at" field.
func ReceivedAtGTE(v time.Time) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldGTE(FieldReceivedAt, v))
}

// ReceivedAtLT applies the LT predicate on the "received_at" field.
func ReceivedAtLT(v time.Time) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldLT(FieldReceivedAt, v))
}

// ReceivedAtLTE applies the LTE predicate on the "received_at" field.
func ReceivedAtLTE(v time.Time) predicate.StoreEvent {
	return predicate.StoreEvent(sql.FieldLTE(FieldReceivedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StoreEvent) predicate.StoreEvent {
	return predicate.StoreEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StoreEvent) predicate.StoreEvent {
	return predicate.StoreEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StoreEvent) predicate.StoreEvent {
	return predicate.StoreEvent(sql.NotPredicates(p))
}
