// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocking

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewTransactor creates a new instance of Transactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Transactor {
	mock := &Transactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Transactor is an autogenerated mock type for the Transactor type
type Transactor struct {
	mock.Mock
}

type Transactor_Expecter struct {
	mock *mock.Mock
}

func (_m *Transactor) EXPECT() *Transactor_Expecter {
	return &Transactor_Expecter{mock: &_m.Mock}
}

// Tx provides a mock function for the type Transactor
func (_mock *Transactor) Tx(ctx context.Context, f func(context.Context) error) error {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Tx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = returnFunc(ctx, f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Transactor_Tx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tx'
type Transactor_Tx_Call struct {
	*mock.Call
}

// Tx is a helper method to define mock.On call
//   - ctx context.Context
//   - f func(context.Context) error
func (_e *Transactor_Expecter) Tx(ctx interface{}, f interface{}) *Transactor_Tx_Call {
	return &Transactor_Tx_Call{Call: _e.mock.On("Tx", ctx, f)}
}

func (_c *Transactor_Tx_Call) Run(run func(ctx context.Context, f func(context.Context) error)) *Transactor_Tx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Transactor_Tx_Call) Return(err error) *Transactor_Tx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Transactor_Tx_Call) RunAndReturn(run func(ctx context.Context, f func(context.Context) error) error) *Transactor_Tx_Call {
	_c.Call.Return(run)
	return _c
}
