// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EntitlementsColumns holds the columns for the "entitlements" table.
	EntitlementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString, Unique: true},
		{Name: "source", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "last_changed_at", Type: field.TypeTime, Nullable: true},
		{Name: "reason", Type: field.TypeString},
	}
	// EntitlementsTable holds the schema information for the "entitlements" table.
	EntitlementsTable = &schema.Table{
		Name:       "entitlements",
		Columns:    EntitlementsColumns,
		PrimaryKey: []*schema.Column{EntitlementsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "entitlement_source",
				Unique:  false,
				Columns: []*schema.Column{EntitlementsColumns[2]},
			},
		},
	}
	// StoreEventsColumns holds the columns for the "store_events" table.
	StoreEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "event_id", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "event_time_ms", Type: field.TypeInt64},
		{Name: "product_id", Type: field.TypeString},
		{Name: "received_at", Type: field.TypeTime},
	}
	// StoreEventsTable holds the schema information for the "store_events" table.
	StoreEventsTable = &schema.Table{
		Name:       "store_events",
		Columns:    StoreEventsColumns,
		PrimaryKey: []*schema.Column{StoreEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "storeevent_user_id",
				Unique:  false,
				Columns: []*schema.Column{StoreEventsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EntitlementsTable,
		StoreEventsTable,
	}
)

func init() {
}
