// Code generated by ent, DO NOT EDIT.

package ent

import (
	"adora-test/ent/entitlement"
	"adora-test/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntitlementUpdate is the builder for updating Entitlement entities.
type EntitlementUpdate struct {
	config
	hooks    []Hook
	mutation *EntitlementMutation
}

// Where appends a list predicates to the EntitlementUpdate builder.
func (_u *EntitlementUpdate) Where(ps ...predicate.Entitlement) *EntitlementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EntitlementUpdate) SetUserID(v string) *EntitlementUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableUserID(v *string) *EntitlementUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *EntitlementUpdate) SetSource(v string) *EntitlementUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableSource(v *string) *EntitlementUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *EntitlementUpdate) SetIsActive(v bool) *EntitlementUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableIsActive(v *bool) *EntitlementUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EntitlementUpdate) SetExpiresAt(v time.Time) *EntitlementUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableExpiresAt(v *time.Time) *EntitlementUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetLastChangedAt sets the "last_changed_at" field.
func (_u *EntitlementUpdate) SetLastChangedAt(v time.Time) *EntitlementUpdate {
	_u.mutation.SetLastChangedAt(v)
	return _u
}

// SetNillableLastChangedAt sets the "last_changed_at" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableLastChangedAt(v *time.Time) *EntitlementUpdate {
	if v != nil {
		_u.SetLastChangedAt(*v)
	}
	return _u
}

// ClearLastChangedAt clears the value of the "last_changed_at" field.
func (_u *EntitlementUpdate) ClearLastChangedAt() *EntitlementUpdate {
	_u.mutation.ClearLastChangedAt()
	return _u
}

// SetReason sets the "reason" field.
func (_u *EntitlementUpdate) SetReason(v string) *EntitlementUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableReason(v *string) *EntitlementUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetLastPolledAt sets the "last_polled_at" field.
func (_u *EntitlementUpdate) SetLastPolledAt(v time.Time) *EntitlementUpdate {
	_u.mutation.SetLastPolledAt(v)
	return _u
}

// SetNillableLastPolledAt sets the "last_polled_at" field if the given value is not nil.
func (_u *EntitlementUpdate) SetNillableLastPolledAt(v *time.Time) *EntitlementUpdate {
	if v != nil {
		_u.SetLastPolledAt(*v)
	}
	return _u
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (_u *EntitlementUpdate) ClearLastPolledAt() *EntitlementUpdate {
	_u.mutation.ClearLastPolledAt()
	return _u
}

// Mutation returns the EntitlementMutation object of the builder.
func (_u *EntitlementUpdate) Mutation() *EntitlementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntitlementUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntitlementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntitlementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntitlementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EntitlementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(entitlement.Table, entitlement.Columns, sqlgraph.NewFieldSpec(entitlement.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(entitlement.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(entitlement.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(entitlement.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(entitlement.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastChangedAt(); ok {
		_spec.SetField(entitlement.FieldLastChangedAt, field.TypeTime, value)
	}
	if _u.mutation.LastChangedAtCleared() {
		_spec.ClearField(entitlement.FieldLastChangedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(entitlement.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastPolledAt(); ok {
		_spec.SetField(entitlement.FieldLastPolledAt, field.TypeTime, value)
	}
	if _u.mutation.LastPolledAtCleared() {
		_spec.ClearField(entitlement.FieldLastPolledAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntitlementUpdateOne is the builder for updating a single Entitlement entity.
type EntitlementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntitlementMutation
}

// SetUserID sets the "user_id" field.
func (_u *EntitlementUpdateOne) SetUserID(v string) *EntitlementUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableUserID(v *string) *EntitlementUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *EntitlementUpdateOne) SetSource(v string) *EntitlementUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableSource(v *string) *EntitlementUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *EntitlementUpdateOne) SetIsActive(v bool) *EntitlementUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableIsActive(v *bool) *EntitlementUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EntitlementUpdateOne) SetExpiresAt(v time.Time) *EntitlementUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableExpiresAt(v *time.Time) *EntitlementUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetLastChangedAt sets the "last_changed_at" field.
func (_u *EntitlementUpdateOne) SetLastChangedAt(v time.Time) *EntitlementUpdateOne {
	_u.mutation.SetLastChangedAt(v)
	return _u
}

// SetNillableLastChangedAt sets the "last_changed_at" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableLastChangedAt(v *time.Time) *EntitlementUpdateOne {
	if v != nil {
		_u.SetLastChangedAt(*v)
	}
	return _u
}

// ClearLastChangedAt clears the value of the "last_changed_at" field.
func (_u *EntitlementUpdateOne) ClearLastChangedAt() *EntitlementUpdateOne {
	_u.mutation.ClearLastChangedAt()
	return _u
}

// SetReason sets the "reason" field.
func (_u *EntitlementUpdateOne) SetReason(v string) *EntitlementUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableReason(v *string) *EntitlementUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetLastPolledAt sets the "last_polled_at" field.
func (_u *EntitlementUpdateOne) SetLastPolledAt(v time.Time) *EntitlementUpdateOne {
	_u.mutation.SetLastPolledAt(v)
	return _u
}

// SetNillableLastPolledAt sets the "last_polled_at" field if the given value is not nil.
func (_u *EntitlementUpdateOne) SetNillableLastPolledAt(v *time.Time) *EntitlementUpdateOne {
	if v != nil {
		_u.SetLastPolledAt(*v)
	}
	return _u
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (_u *EntitlementUpdateOne) ClearLastPolledAt() *EntitlementUpdateOne {
	_u.mutation.ClearLastPolledAt()
	return _u
}

// Mutation returns the EntitlementMutation object of the builder.
func (_u *EntitlementUpdateOne) Mutation() *EntitlementMutation {
	return _u.mutation
}

// Where appends a list predicates to the EntitlementUpdate builder.
func (_u *EntitlementUpdateOne) Where(ps ...predicate.Entitlement) *EntitlementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntitlementUpdateOne) Select(field string, fields ...string) *EntitlementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Entitlement entity.
func (_u *EntitlementUpdateOne) Save(ctx context.Context) (*Entitlement, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntitlementUpdateOne) SaveX(ctx context.Context) *Entitlement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntitlementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntitlementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EntitlementUpdateOne) sqlSave(ctx context.Context) (_node *Entitlement, err error) {
	_spec := sqlgraph.NewUpdateSpec(entitlement.Table, entitlement.Columns, sqlgraph.NewFieldSpec(entitlement.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Entitlement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entitlement.FieldID)
		for _, f := range fields {
			if !entitlement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entitlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(entitlement.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(entitlement.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(entitlement.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(entitlement.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastChangedAt(); ok {
		_spec.SetField(entitlement.FieldLastChangedAt, field.TypeTime, value)
	}
	if _u.mutation.LastChangedAtCleared() {
		_spec.ClearField(entitlement.FieldLastChangedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(entitlement.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastPolledAt(); ok {
		_spec.SetField(entitlement.FieldLastPolledAt, field.TypeTime, value)
	}
	if _u.mutation.LastPolledAtCleared() {
		_spec.ClearField(entitlement.FieldLastPolledAt, field.TypeTime)
	}
	_node = &Entitlement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
