// Code generated by ent, DO NOT EDIT.

package ent

import (
	"adora-test/ent/entitlement"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntitlementCreate is the builder for creating a Entitlement entity.
type EntitlementCreate struct {
	config
	mutation *EntitlementMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *EntitlementCreate) SetUserID(v string) *EntitlementCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *EntitlementCreate) SetSource(v string) *EntitlementCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *EntitlementCreate) SetIsActive(v bool) *EntitlementCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *EntitlementCreate) SetExpiresAt(v time.Time) *EntitlementCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetLastChangedAt sets the "last_changed_at" field.
func (_c *EntitlementCreate) SetLastChangedAt(v time.Time) *EntitlementCreate {
	_c.mutation.SetLastChangedAt(v)
	return _c
}

// SetNillableLastChangedAt sets the "last_changed_at" field if the given value is not nil.
func (_c *EntitlementCreate) SetNillableLastChangedAt(v *time.Time) *EntitlementCreate {
	if v != nil {
		_c.SetLastChangedAt(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *EntitlementCreate) SetReason(v string) *EntitlementCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetLastPolledAt sets the "last_polled_at" field.
func (_c *EntitlementCreate) SetLastPolledAt(v time.Time) *EntitlementCreate {
	_c.mutation.SetLastPolledAt(v)
	return _c
}

// SetNillableLastPolledAt sets the "last_polled_at" field if the given value is not nil.
func (_c *EntitlementCreate) SetNillableLastPolledAt(v *time.Time) *EntitlementCreate {
	if v != nil {
		_c.SetLastPolledAt(*v)
	}
	return _c
}

// Mutation returns the EntitlementMutation object of the builder.
func (_c *EntitlementCreate) Mutation() *EntitlementMutation {
	return _c.mutation
}

// Save creates the Entitlement in the database.
func (_c *EntitlementCreate) Save(ctx context.Context) (*Entitlement, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EntitlementCreate) SaveX(ctx context.Context) *Entitlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntitlementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntitlementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EntitlementCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Entitlement.user_id"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Entitlement.source"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Entitlement.is_active"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "Entitlement.expires_at"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "Entitlement.reason"`)}
	}
	return nil
}

func (_c *EntitlementCreate) sqlSave(ctx context.Context) (*Entitlement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EntitlementCreate) createSpec() (*Entitlement, *sqlgraph.CreateSpec) {
	var (
		_node = &Entitlement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entitlement.Table, sqlgraph.NewFieldSpec(entitlement.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(entitlement.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(entitlement.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(entitlement.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(entitlement.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.LastChangedAt(); ok {
		_spec.SetField(entitlement.FieldLastChangedAt, field.TypeTime, value)
		_node.LastChangedAt = &value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(entitlement.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.LastPolledAt(); ok {
		_spec.SetField(entitlement.FieldLastPolledAt, field.TypeTime, value)
		_node.LastPolledAt = &value
	}
	return _node, _spec
}

// EntitlementCreateBulk is the builder for creating many Entitlement entities in bulk.
type EntitlementCreateBulk struct {
	config
	err      error
	builders []*EntitlementCreate
}

// Save creates the Entitlement entities in the database.
func (_c *EntitlementCreateBulk) Save(ctx context.Context) ([]*Entitlement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Entitlement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntitlementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EntitlementCreateBulk) SaveX(ctx context.Context) []*Entitlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntitlementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntitlementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
