// Code generated by ent, DO NOT EDIT.

package ent

import (
	"adora-test/ent/entitlement"
	"adora-test/ent/predicate"
	"adora-test/ent/storeevent"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeEntitlement = "Entitlement"
	TypeStoreEvent  = "StoreEvent"
)

// EntitlementMutation represents an operation that mutates the Entitlement nodes in the graph.
type EntitlementMutation struct {
	config
	op              Op
	typ             string
	id              *int
	user_id         *string
	source          *string
	is_active       *bool
	expires_at      *time.Time
	last_changed_at *time.Time
	reason          *string
	last_polled_at  *time.Time
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*Entitlement, error)
	predicates      []predicate.Entitlement
}

var _ ent.Mutation = (*EntitlementMutation)(nil)

// entitlementOption allows management of the mutation configuration using functional options.
type entitlementOption func(*EntitlementMutation)

// newEntitlementMutation creates new mutation for the Entitlement entity.
func newEntitlementMutation(c config, op Op, opts ...entitlementOption) *EntitlementMutation {
	m := &EntitlementMutation{
		config:        c,
		op:            op,
		typ:           TypeEntitlement,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withEntitlementID sets the ID field of the mutation.
func withEntitlementID(id int) entitlementOption {
	return func(m *EntitlementMutation) {
		var (
			err   error
			once  sync.Once
			value *Entitlement
		)
		m.oldValue = func(ctx context.Context) (*Entitlement, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Entitlement.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withEntitlement sets the old Entitlement of the mutation.
func withEntitlement(node *Entitlement) entitlementOption {
	return func(m *EntitlementMutation) {
		m.oldValue = func(context.Context) (*Entitlement, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m EntitlementMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m EntitlementMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *EntitlementMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *EntitlementMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Entitlement.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserID sets the "user_id" field.
func (m *EntitlementMutation) SetUserID(s string) {
	m.user_id = &s
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *EntitlementMutation) UserID() (r string, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the Entitlement entity.
// If the Entitlement object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EntitlementMutation) OldUserID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *EntitlementMutation) ResetUserID() {
	m.user_id = nil
}

// SetSource sets the "source" field.
func (m *EntitlementMutation) SetSource(s string) {
	m.source = &s
}

// Source returns the value of the "source" field in the mutation.
func (m *EntitlementMutation) Source() (r string, exists bool) {
	v := m.source
	if v == nil {
		return
	}
	return *v, true
}

// OldSource returns the old "source" field's value of the Entitlement entity.
// If the Entitlement object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EntitlementMutation) OldSource(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSource is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSource requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSource: %w", err)
	}
	return oldValue.Source, nil
}

// ResetSource resets all changes to the "source" field.
func (m *EntitlementMutation) ResetSource() {
	m.source = nil
}

// SetIsActive sets the "is_active" field.
func (m *EntitlementMutation) SetIsActive(b bool) {
	m.is_active = &b
}

// IsActive returns the value of the "is_active" field in the mutation.
func (m *EntitlementMutation) IsActive() (r bool, exists bool) {
	v := m.is_active
	if v == nil {
		return
	}
	return *v, true
}

// OldIsActive returns the old "is_active" field's value of the Entitlement entity.
// If the Entitlement object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EntitlementMutation) OldIsActive(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsActive is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsActive requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsActive: %w", err)
	}
	return oldValue.IsActive, nil
}

// ResetIsActive resets all changes to the "is_active" field.
func (m *EntitlementMutation) ResetIsActive() {
	m.is_active = nil
}

// SetExpiresAt sets the "expires_at" field.
func (m *EntitlementMutation) SetExpiresAt(t time.Time) {
	m.expires_at = &t
}

// ExpiresAt returns the value of the "expires_at" field in the mutation.
func (m *EntitlementMutation) ExpiresAt() (r time.Time, exists bool) {
	v := m.expires_at
	if v == nil {
		return
	}
	return *v, true
}

// OldExpiresAt returns the old "expires_at" field's value of the Entitlement entity.
// If the Entitlement object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EntitlementMutation) OldExpiresAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpiresAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpiresAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpiresAt: %w", err)
	}
	return oldValue.ExpiresAt, nil
}

// ResetExpiresAt resets all changes to the "expires_at" field.
func (m *EntitlementMutation) ResetExpiresAt() {
	m.expires_at = nil
}

// SetLastChangedAt sets the "last_changed_at" field.
func (m *EntitlementMutation) SetLastChangedAt(t time.Time) {
	m.last_changed_at = &t
}

// LastChangedAt returns the value of the "last_changed_at" field in the mutation.
func (m *EntitlementMutation) LastChangedAt() (r time.Time, exists bool) {
	v := m.last_changed_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastChangedAt returns the old "last_changed_at" field's value of the Entitlement entity.
// If the Entitlement object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EntitlementMutation) OldLastChangedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastChangedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastChangedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastChangedAt: %w", err)
	}
	return oldValue.LastChangedAt, nil
}

// ClearLastChangedAt clears the value of the "last_changed_at" field.
func (m *EntitlementMutation) ClearLastChangedAt() {
	m.last_changed_at = nil
	m.clearedFields[entitlement.FieldLastChangedAt] = struct{}{}
}

// LastChangedAtCleared returns if the "last_changed_at" field was cleared in this mutation.
func (m *EntitlementMutation) LastChangedAtCleared() bool {
	_, ok := m.clearedFields[entitlement.FieldLastChangedAt]
	return ok
}

// ResetLastChangedAt resets all changes to the "last_changed_at" field.
func (m *EntitlementMutation) ResetLastChangedAt() {
	m.last_changed_at = nil
	delete(m.clearedFields, entitlement.FieldLastChangedAt)
}

// SetReason sets the "reason" field.
func (m *EntitlementMutation) SetReason(s string) {
	m.reason = &s
}

// Reason returns the value of the "reason" field in the mutation.
func (m *EntitlementMutation) Reason() (r string, exists bool) {
	v := m.reason
	if v == nil {
		return
	}
	return *v, true
}

// OldReason returns the old "reason" field's value of the Entitlement entity.
// If the Entitlement object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EntitlementMutation) OldReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReason: %w", err)
	}
	return oldValue.Reason, nil
}

// ResetReason resets all changes to the "reason" field.
func (m *EntitlementMutation) ResetReason() {
	m.reason = nil
}

// SetLastPolledAt sets the "last_polled_at" field.
func (m *EntitlementMutation) SetLastPolledAt(t time.Time) {
	m.last_polled_at = &t
}

// LastPolledAt returns the value of the "last_polled_at" field in the mutation.
func (m *EntitlementMutation) LastPolledAt() (r time.Time, exists bool) {
	v := m.last_polled_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastPolledAt returns the old "last_polled_at" field's value of the Entitlement entity.
// If the Entitlement object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EntitlementMutation) OldLastPolledAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastPolledAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastPolledAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastPolledAt: %w", err)
	}
	return oldValue.LastPolledAt, nil
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (m *EntitlementMutation) ClearLastPolledAt() {
	m.last_polled_at = nil
	m.clearedFields[entitlement.FieldLastPolledAt] = struct{}{}
}

// LastPolledAtCleared returns if the "last_polled_at" field was cleared in this mutation.
func (m *EntitlementMutation) LastPolledAtCleared() bool {
	_, ok := m.clearedFields[entitlement.FieldLastPolledAt]
	return ok
}

// ResetLastPolledAt resets all changes to the "last_polled_at" field.
func (m *EntitlementMutation) ResetLastPolledAt() {
	m.last_polled_at = nil
	delete(m.clearedFields, entitlement.FieldLastPolledAt)
}

// Where appends a list predicates to the EntitlementMutation builder.
func (m *EntitlementMutation) Where(ps ...predicate.Entitlement) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the EntitlementMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *EntitlementMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Entitlement, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *EntitlementMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *EntitlementMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Entitlement).
func (m *EntitlementMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *EntitlementMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.user_id != nil {
		fields = append(fields, entitlement.FieldUserID)
	}
	if m.source != nil {
		fields = append(fields, entitlement.FieldSource)
	}
	if m.is_active != nil {
		fields = append(fields, entitlement.FieldIsActive)
	}
	if m.expires_at != nil {
		fields = append(fields, entitlement.FieldExpiresAt)
	}
	if m.last_changed_at != nil {
		fields = append(fields, entitlement.FieldLastChangedAt)
	}
	if m.reason != nil {
		fields = append(fields, entitlement.FieldReason)
	}
	if m.last_polled_at != nil {
		fields = append(fields, entitlement.FieldLastPolledAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *EntitlementMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case entitlement.FieldUserID:
		return m.UserID()
	case entitlement.FieldSource:
		return m.Source()
	case entitlement.FieldIsActive:
		return m.IsActive()
	case entitlement.FieldExpiresAt:
		return m.ExpiresAt()
	case entitlement.FieldLastChangedAt:
		return m.LastChangedAt()
	case entitlement.FieldReason:
		return m.Reason()
	case entitlement.FieldLastPolledAt:
		return m.LastPolledAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *EntitlementMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case entitlement.FieldUserID:
		return m.OldUserID(ctx)
	case entitlement.FieldSource:
		return m.OldSource(ctx)
	case entitlement.FieldIsActive:
		return m.OldIsActive(ctx)
	case entitlement.FieldExpiresAt:
		return m.OldExpiresAt(ctx)
	case entitlement.FieldLastChangedAt:
		return m.OldLastChangedAt(ctx)
	case entitlement.FieldReason:
		return m.OldReason(ctx)
	case entitlement.FieldLastPolledAt:
		return m.OldLastPolledAt(ctx)
	}
	return nil, fmt.Errorf("unknown Entitlement field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EntitlementMutation) SetField(name string, value ent.Value) error {
	switch name {
	case entitlement.FieldUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case entitlement.FieldSource:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSource(v)
		return nil
	case entitlement.FieldIsActive:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsActive(v)
		return nil
	case entitlement.FieldExpiresAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpiresAt(v)
		return nil
	case entitlement.FieldLastChangedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastChangedAt(v)
		return nil
	case entitlement.FieldReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReason(v)
		return nil
	case entitlement.FieldLastPolledAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastPolledAt(v)
		return nil
	}
	return fmt.Errorf("unknown Entitlement field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *EntitlementMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *EntitlementMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EntitlementMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Entitlement numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *EntitlementMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(entitlement.FieldLastChangedAt) {
		fields = append(fields, entitlement.FieldLastChangedAt)
	}
	if m.FieldCleared(entitlement.FieldLastPolledAt) {
		fields = append(fields, entitlement.FieldLastPolledAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *EntitlementMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *EntitlementMutation) ClearField(name string) error {
	switch name {
	case entitlement.FieldLastChangedAt:
		m.ClearLastChangedAt()
		return nil
	case entitlement.FieldLastPolledAt:
		m.ClearLastPolledAt()
		return nil
	}
	return fmt.Errorf("unknown Entitlement nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *EntitlementMutation) ResetField(name string) error {
	switch name {
	case entitlement.FieldUserID:
		m.ResetUserID()
		return nil
	case entitlement.FieldSource:
		m.ResetSource()
		return nil
	case entitlement.FieldIsActive:
		m.ResetIsActive()
		return nil
	case entitlement.FieldExpiresAt:
		m.ResetExpiresAt()
		return nil
	case entitlement.FieldLastChangedAt:
		m.ResetLastChangedAt()
		return nil
	case entitlement.FieldReason:
		m.ResetReason()
		return nil
	case entitlement.FieldLastPolledAt:
		m.ResetLastPolledAt()
		return nil
	}
	return fmt.Errorf("unknown Entitlement field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *EntitlementMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *EntitlementMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *EntitlementMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *EntitlementMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *EntitlementMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *EntitlementMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *EntitlementMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Entitlement unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *EntitlementMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Entitlement edge %s", name)
}

// StoreEventMutation represents an operation that mutates the StoreEvent nodes in the graph.
type StoreEventMutation struct {
	config
	op               Op
	typ              string
	id               *int
	event_id         *string
	user_id          *string
	_type            *string
	event_time_ms    *int64
	addevent_time_ms *int64
	product_id       *string
	received_at      *time.Time
	clearedFields    map[string]struct{}
	done             bool
	oldValue         func(context.Context) (*StoreEvent, error)
	predicates       []predicate.StoreEvent
}

var _ ent.Mutation = (*StoreEventMutation)(nil)

// storeeventOption allows management of the mutation configuration using functional options.
type storeeventOption func(*StoreEventMutation)

// newStoreEventMutation creates new mutation for the StoreEvent entity.
func newStoreEventMutation(c config, op Op, opts ...storeeventOption) *StoreEventMutation {
	m := &StoreEventMutation{
		config:        c,
		op:            op,
		typ:           TypeStoreEvent,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withStoreEventID sets the ID field of the mutation.
func withStoreEventID(id int) storeeventOption {
	return func(m *StoreEventMutation) {
		var (
			err   error
			once  sync.Once
			value *StoreEvent
		)
		m.oldValue = func(ctx context.Context) (*StoreEvent, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().StoreEvent.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withStoreEvent sets the old StoreEvent of the mutation.
func withStoreEvent(node *StoreEvent) storeeventOption {
	return func(m *StoreEventMutation) {
		m.oldValue = func(context.Context) (*StoreEvent, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m StoreEventMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m StoreEventMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *StoreEventMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *StoreEventMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().StoreEvent.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetEventID sets the "event_id" field.
func (m *StoreEventMutation) SetEventID(s string) {
	m.event_id = &s
}

// EventID returns the value of the "event_id" field in the mutation.
func (m *StoreEventMutation) EventID() (r string, exists bool) {
	v := m.event_id
	if v == nil {
		return
	}
	return *v, true
}

// OldEventID returns the old "event_id" field's value of the StoreEvent entity.
// If the StoreEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreEventMutation) OldEventID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEventID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEventID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEventID: %w", err)
	}
	return oldValue.EventID, nil
}

// ResetEventID resets all changes to the "event_id" field.
func (m *StoreEventMutation) ResetEventID() {
	m.event_id = nil
}

// SetUserID sets the "user_id" field.
func (m *StoreEventMutation) SetUserID(s string) {
	m.user_id = &s
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *StoreEventMutation) UserID() (r string, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the StoreEvent entity.
// If the StoreEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreEventMutation) OldUserID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *StoreEventMutation) ResetUserID() {
	m.user_id = nil
}

// SetType sets the "type" field.
func (m *StoreEventMutation) SetType(s string) {
	m._type = &s
}

// GetType returns the value of the "type" field in the mutation.
func (m *StoreEventMutation) GetType() (r string, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the StoreEvent entity.
// If the StoreEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreEventMutation) OldType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *StoreEventMutation) ResetType() {
	m._type = nil
}

// SetEventTimeMs sets the "event_time_ms" field.
func (m *StoreEventMutation) SetEventTimeMs(i int64) {
	m.event_time_ms = &i
	m.addevent_time_ms = nil
}

// EventTimeMs returns the value of the "event_time_ms" field in the mutation.
func (m *StoreEventMutation) EventTimeMs() (r int64, exists bool) {
	v := m.event_time_ms
	if v == nil {
		return
	}
	return *v, true
}

// OldEventTimeMs returns the old "event_time_ms" field's value of the StoreEvent entity.
// If the StoreEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreEventMutation) OldEventTimeMs(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEventTimeMs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEventTimeMs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEventTimeMs: %w", err)
	}
	return oldValue.EventTimeMs, nil
}

// AddEventTimeMs adds i to the "event_time_ms" field.
func (m *StoreEventMutation) AddEventTimeMs(i int64) {
	if m.addevent_time_ms != nil {
		*m.addevent_time_ms += i
	} else {
		m.addevent_time_ms = &i
	}
}

// AddedEventTimeMs returns the value that was added to the "event_time_ms" field in this mutation.
func (m *StoreEventMutation) AddedEventTimeMs() (r int64, exists bool) {
	v := m.addevent_time_ms
	if v == nil {
		return
	}
	return *v, true
}

// ResetEventTimeMs resets all changes to the "event_time_ms" field.
func (m *StoreEventMutation) ResetEventTimeMs() {
	m.event_time_ms = nil
	m.addevent_time_ms = nil
}

// SetProductID sets the "product_id" field.
func (m *StoreEventMutation) SetProductID(s string) {
	m.product_id = &s
}

// ProductID returns the value of the "product_id" field in the mutation.
func (m *StoreEventMutation) ProductID() (r string, exists bool) {
	v := m.product_id
	if v == nil {
		return
	}
	return *v, true
}

// OldProductID returns the old "product_id" field's value of the StoreEvent entity.
// If the StoreEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreEventMutation) OldProductID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProductID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProductID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProductID: %w", err)
	}
	return oldValue.ProductID, nil
}

// ResetProductID resets all changes to the "product_id" field.
func (m *StoreEventMutation) ResetProductID() {
	m.product_id = nil
}

// SetReceivedAt sets the "received_at" field.
func (m *StoreEventMutation) SetReceivedAt(t time.Time) {
	m.received_at = &t
}

// ReceivedAt returns the value of the "received_at" field in the mutation.
func (m *StoreEventMutation) ReceivedAt() (r time.Time, exists bool) {
	v := m.received_at
	if v == nil {
		return
	}
	return *v, true
}

// OldReceivedAt returns the old "received_at" field's value of the StoreEvent entity.
// If the StoreEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreEventMutation) OldReceivedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReceivedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReceivedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReceivedAt: %w", err)
	}
	return oldValue.ReceivedAt, nil
}

// ResetReceivedAt resets all changes to the "received_at" field.
func (m *StoreEventMutation) ResetReceivedAt() {
	m.received_at = nil
}

// Where appends a list predicates to the StoreEventMutation builder.
func (m *StoreEventMutation) Where(ps ...predicate.StoreEvent) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the StoreEventMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *StoreEventMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.StoreEvent, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *StoreEventMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *StoreEventMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (StoreEvent).
func (m *StoreEventMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *StoreEventMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.event_id != nil {
		fields = append(fields, storeevent.FieldEventID)
	}
	if m.user_id != nil {
		fields = append(fields, storeevent.FieldUserID)
	}
	if m._type != nil {
		fields = append(fields, storeevent.FieldType)
	}
	if m.event_time_ms != nil {
		fields = append(fields, storeevent.FieldEventTimeMs)
	}
	if m.product_id != nil {
		fields = append(fields, storeevent.FieldProductID)
	}
	if m.received_at != nil {
		fields = append(fields, storeevent.FieldReceivedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *StoreEventMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case storeevent.FieldEventID:
		return m.EventID()
	case storeevent.FieldUserID:
		return m.UserID()
	case storeevent.FieldType:
		return m.GetType()
	case storeevent.FieldEventTimeMs:
		return m.EventTimeMs()
	case storeevent.FieldProductID:
		return m.ProductID()
	case storeevent.FieldReceivedAt:
		return m.ReceivedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *StoreEventMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case storeevent.FieldEventID:
		return m.OldEventID(ctx)
	case storeevent.FieldUserID:
		return m.OldUserID(ctx)
	case storeevent.FieldType:
		return m.OldType(ctx)
	case storeevent.FieldEventTimeMs:
		return m.OldEventTimeMs(ctx)
	case storeevent.FieldProductID:
		return m.OldProductID(ctx)
	case storeevent.FieldReceivedAt:
		return m.OldReceivedAt(ctx)
	}
	return nil, fmt.Errorf("unknown StoreEvent field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StoreEventMutation) SetField(name string, value ent.Value) error {
	switch name {
	case storeevent.FieldEventID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEventID(v)
		return nil
	case storeevent.FieldUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case storeevent.FieldType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case storeevent.FieldEventTimeMs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEventTimeMs(v)
		return nil
	case storeevent.FieldProductID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProductID(v)
		return nil
	case storeevent.FieldReceivedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReceivedAt(v)
		return nil
	}
	return fmt.Errorf("unknown StoreEvent field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *StoreEventMutation) AddedFields() []string {
	var fields []string
	if m.addevent_time_ms != nil {
		fields = append(fields, storeevent.FieldEventTimeMs)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *StoreEventMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case storeevent.FieldEventTimeMs:
		return m.AddedEventTimeMs()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StoreEventMutation) AddField(name string, value ent.Value) error {
	switch name {
	case storeevent.FieldEventTimeMs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddEventTimeMs(v)
		return nil
	}
	return fmt.Errorf("unknown StoreEvent numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *StoreEventMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *StoreEventMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *StoreEventMutation) ClearField(name string) error {
	return fmt.Errorf("unknown StoreEvent nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *StoreEventMutation) ResetField(name string) error {
	switch name {
	case storeevent.FieldEventID:
		m.ResetEventID()
		return nil
	case storeevent.FieldUserID:
		m.ResetUserID()
		return nil
	case storeevent.FieldType:
		m.ResetType()
		return nil
	case storeevent.FieldEventTimeMs:
		m.ResetEventTimeMs()
		return nil
	case storeevent.FieldProductID:
		m.ResetProductID()
		return nil
	case storeevent.FieldReceivedAt:
		m.ResetReceivedAt()
		return nil
	}
	return fmt.Errorf("unknown StoreEvent field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *StoreEventMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *StoreEventMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *StoreEventMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *StoreEventMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *StoreEventMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *StoreEventMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *StoreEventMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown StoreEvent unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *StoreEventMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown StoreEvent edge %s", name)
}
