// Code generated by ent, DO NOT EDIT.

package ent

import (
	"adora-test/ent/schema"
	"adora-test/ent/storeevent"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	storeeventFields := schema.StoreEvent{}.Fields()
	_ = storeeventFields
	// storeeventDescReceivedAt is the schema descriptor for received_at field.
	storeeventDescReceivedAt := storeeventFields[5].Descriptor()
	// storeevent.DefaultReceivedAt holds the default value on creation for the received_at field.
	storeevent.DefaultReceivedAt = storeeventDescReceivedAt.Default.(func() time.Time)
}
