// Code generated by ent, DO NOT EDIT.

package ent

import (
	"adora-test/ent/storeevent"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StoreEventCreate is the builder for creating a StoreEvent entity.
type StoreEventCreate struct {
	config
	mutation *StoreEventMutation
	hooks    []Hook
}

// SetEventID sets the "event_id" field.
func (_c *StoreEventCreate) SetEventID(v string) *StoreEventCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *StoreEventCreate) SetUserID(v string) *StoreEventCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *StoreEventCreate) SetType(v string) *StoreEventCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetEventTimeMs sets the "event_time_ms" field.
func (_c *StoreEventCreate) SetEventTimeMs(v int64) *StoreEventCreate {
	_c.mutation.SetEventTimeMs(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *StoreEventCreate) SetProductID(v string) *StoreEventCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetReceivedAt sets the "received_at" field.
func (_c *StoreEventCreate) SetReceivedAt(v time.Time) *StoreEventCreate {
	_c.mutation.SetReceivedAt(v)
	return _c
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_c *StoreEventCreate) SetNillableReceivedAt(v *time.Time) *StoreEventCreate {
	if v != nil {
		_c.SetReceivedAt(*v)
	}
	return _c
}

// Mutation returns the StoreEventMutation object of the builder.
func (_c *StoreEventCreate) Mutation() *StoreEventMutation {
	return _c.mutation
}

// Save creates the StoreEvent in the database.
func (_c *StoreEventCreate) Save(ctx context.Context) (*StoreEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StoreEventCreate) SaveX(ctx context.Context) *StoreEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StoreEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StoreEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StoreEventCreate) defaults() {
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		v := storeevent.DefaultReceivedAt()
		_c.mutation.SetReceivedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StoreEventCreate) check() error {
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "StoreEvent.event_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "StoreEvent.user_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "StoreEvent.type"`)}
	}
	if _, ok := _c.mutation.EventTimeMs(); !ok {
		return &ValidationError{Name: "event_time_ms", err: errors.New(`ent: missing required field "StoreEvent.event_time_ms"`)}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "StoreEvent.product_id"`)}
	}
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		return &ValidationError{Name: "received_at", err: errors.New(`ent: missing required field "StoreEvent.received_at"`)}
	}
	return nil
}

func (_c *StoreEventCreate) sqlSave(ctx context.Context) (*StoreEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StoreEventCreate) createSpec() (*StoreEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &StoreEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(storeevent.Table, sqlgraph.NewFieldSpec(storeevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.EventID(); ok {
		_spec.SetField(storeevent.FieldEventID, field.TypeString, value)
		_node.EventID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(storeevent.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(storeevent.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.EventTimeMs(); ok {
		_spec.SetField(storeevent.FieldEventTimeMs, field.TypeInt64, value)
		_node.EventTimeMs = value
	}
	if value, ok := _c.mutation.ProductID(); ok {
		_spec.SetField(storeevent.FieldProductID, field.TypeString, value)
		_node.ProductID = value
	}
	if value, ok := _c.mutation.ReceivedAt(); ok {
		_spec.SetField(storeevent.FieldReceivedAt, field.TypeTime, value)
		_node.ReceivedAt = value
	}
	return _node, _spec
}

// StoreEventCreateBulk is the builder for creating many StoreEvent entities in bulk.
type StoreEventCreateBulk struct {
	config
	err      error
	builders []*StoreEventCreate
}

// Save creates the StoreEvent entities in the database.
func (_c *StoreEventCreateBulk) Save(ctx context.Context) ([]*StoreEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StoreEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StoreEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StoreEventCreateBulk) SaveX(ctx context.Context) []*StoreEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StoreEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StoreEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
