// Code generated by ent, DO NOT EDIT.

package ent

import (
	"adora-test/ent/predicate"
	"adora-test/ent/storeevent"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StoreEventUpdate is the builder for updating StoreEvent entities.
type StoreEventUpdate struct {
	config
	hooks    []Hook
	mutation *StoreEventMutation
}

// Where appends a list predicates to the StoreEventUpdate builder.
func (_u *StoreEventUpdate) Where(ps ...predicate.StoreEvent) *StoreEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *StoreEventUpdate) SetEventID(v string) *StoreEventUpdate {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *StoreEventUpdate) SetNillableEventID(v *string) *StoreEventUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *StoreEventUpdate) SetUserID(v string) *StoreEventUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *StoreEventUpdate) SetNillableUserID(v *string) *StoreEventUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *StoreEventUpdate) SetType(v string) *StoreEventUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *StoreEventUpdate) SetNillableType(v *string) *StoreEventUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetEventTimeMs sets the "event_time_ms" field.
func (_u *StoreEventUpdate) SetEventTimeMs(v int64) *StoreEventUpdate {
	_u.mutation.ResetEventTimeMs()
	_u.mutation.SetEventTimeMs(v)
	return _u
}

// SetNillableEventTimeMs sets the "event_time_ms" field if the given value is not nil.
func (_u *StoreEventUpdate) SetNillableEventTimeMs(v *int64) *StoreEventUpdate {
	if v != nil {
		_u.SetEventTimeMs(*v)
	}
	return _u
}

// AddEventTimeMs adds value to the "event_time_ms" field.
func (_u *StoreEventUpdate) AddEventTimeMs(v int64) *StoreEventUpdate {
	_u.mutation.AddEventTimeMs(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *StoreEventUpdate) SetProductID(v string) *StoreEventUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *StoreEventUpdate) SetNillableProductID(v *string) *StoreEventUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetReceivedAt sets the "received_at" field.
func (_u *StoreEventUpdate) SetReceivedAt(v time.Time) *StoreEventUpdate {
	_u.mutation.SetReceivedAt(v)
	return _u
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_u *StoreEventUpdate) SetNillableReceivedAt(v *time.Time) *StoreEventUpdate {
	if v != nil {
		_u.SetReceivedAt(*v)
	}
	return _u
}

// Mutation returns the StoreEventMutation object of the builder.
func (_u *StoreEventUpdate) Mutation() *StoreEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StoreEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StoreEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StoreEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StoreEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *StoreEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(storeevent.Table, storeevent.Columns, sqlgraph.NewFieldSpec(storeevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(storeevent.FieldEventID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(storeevent.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(storeevent.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventTimeMs(); ok {
		_spec.SetField(storeevent.FieldEventTimeMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEventTimeMs(); ok {
		_spec.AddField(storeevent.FieldEventTimeMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(storeevent.FieldProductID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReceivedAt(); ok {
		_spec.SetField(storeevent.FieldReceivedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storeevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StoreEventUpdateOne is the builder for updating a single StoreEvent entity.
type StoreEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StoreEventMutation
}

// SetEventID sets the "event_id" field.
func (_u *StoreEventUpdateOne) SetEventID(v string) *StoreEventUpdateOne {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *StoreEventUpdateOne) SetNillableEventID(v *string) *StoreEventUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *StoreEventUpdateOne) SetUserID(v string) *StoreEventUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *StoreEventUpdateOne) SetNillableUserID(v *string) *StoreEventUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *StoreEventUpdateOne) SetType(v string) *StoreEventUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *StoreEventUpdateOne) SetNillableType(v *string) *StoreEventUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetEventTimeMs sets the "event_time_ms" field.
func (_u *StoreEventUpdateOne) SetEventTimeMs(v int64) *StoreEventUpdateOne {
	_u.mutation.ResetEventTimeMs()
	_u.mutation.SetEventTimeMs(v)
	return _u
}

// SetNillableEventTimeMs sets the "event_time_ms" field if the given value is not nil.
func (_u *StoreEventUpdateOne) SetNillableEventTimeMs(v *int64) *StoreEventUpdateOne {
	if v != nil {
		_u.SetEventTimeMs(*v)
	}
	return _u
}

// AddEventTimeMs adds value to the "event_time_ms" field.
func (_u *StoreEventUpdateOne) AddEventTimeMs(v int64) *StoreEventUpdateOne {
	_u.mutation.AddEventTimeMs(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *StoreEventUpdateOne) SetProductID(v string) *StoreEventUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *StoreEventUpdateOne) SetNillableProductID(v *string) *StoreEventUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetReceivedAt sets the "received_at" field.
func (_u *StoreEventUpdateOne) SetReceivedAt(v time.Time) *StoreEventUpdateOne {
	_u.mutation.SetReceivedAt(v)
	return _u
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_u *StoreEventUpdateOne) SetNillableReceivedAt(v *time.Time) *StoreEventUpdateOne {
	if v != nil {
		_u.SetReceivedAt(*v)
	}
	return _u
}

// Mutation returns the StoreEventMutation object of the builder.
func (_u *StoreEventUpdateOne) Mutation() *StoreEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the StoreEventUpdate builder.
func (_u *StoreEventUpdateOne) Where(ps ...predicate.StoreEvent) *StoreEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StoreEventUpdateOne) Select(field string, fields ...string) *StoreEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StoreEvent entity.
func (_u *StoreEventUpdateOne) Save(ctx context.Context) (*StoreEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StoreEventUpdateOne) SaveX(ctx context.Context) *StoreEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StoreEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StoreEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *StoreEventUpdateOne) sqlSave(ctx context.Context) (_node *StoreEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(storeevent.Table, storeevent.Columns, sqlgraph.NewFieldSpec(storeevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StoreEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storeevent.FieldID)
		for _, f := range fields {
			if !storeevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != storeevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(storeevent.FieldEventID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(storeevent.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(storeevent.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventTimeMs(); ok {
		_spec.SetField(storeevent.FieldEventTimeMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEventTimeMs(); ok {
		_spec.AddField(storeevent.FieldEventTimeMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(storeevent.FieldProductID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReceivedAt(); ok {
		_spec.SetField(storeevent.FieldReceivedAt, field.TypeTime, value)
	}
	_node = &StoreEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storeevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
