// Code generated by ent, DO NOT EDIT.

package ent

import (
	"adora-test/ent/storeevent"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// StoreEvent is the model entity for the StoreEvent schema.
type StoreEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EventID holds the value of the "event_id" field.
	EventID string `json:"event_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// EventTimeMs holds the value of the "event_time_ms" field.
	EventTimeMs int64 `json:"event_time_ms,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID string `json:"product_id,omitempty"`
	// ReceivedAt holds the value of the "received_at" field.
	ReceivedAt   time.Time `json:"received_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StoreEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case storeevent.FieldID, storeevent.FieldEventTimeMs:
			values[i] = new(sql.NullInt64)
		case storeevent.FieldEventID, storeevent.FieldUserID, storeevent.FieldType, storeevent.FieldProductID:
			values[i] = new(sql.NullString)
		case storeevent.FieldReceivedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StoreEvent fields.
func (_m *StoreEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case storeevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case storeevent.FieldEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value.Valid {
				_m.EventID = value.String
			}
		case storeevent.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case storeevent.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case storeevent.FieldEventTimeMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field event_time_ms", values[i])
			} else if value.Valid {
				_m.EventTimeMs = value.Int64
			}
		case storeevent.FieldProductID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = value.String
			}
		case storeevent.FieldReceivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_at", values[i])
			} else if value.Valid {
				_m.ReceivedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StoreEvent.
// This includes values selected through modifiers, order, etc.
func (_m *StoreEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this StoreEvent.
// Note that you need to call StoreEvent.Unwrap() before calling this method if this StoreEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StoreEvent) Update() *StoreEventUpdateOne {
	return NewStoreEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StoreEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StoreEvent) Unwrap() *StoreEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StoreEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StoreEvent) String() string {
	var builder strings.Builder
	builder.WriteString("StoreEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_id=")
	builder.WriteString(_m.EventID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("event_time_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventTimeMs))
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(_m.ProductID)
	builder.WriteString(", ")
	builder.WriteString("received_at=")
	builder.WriteString(_m.ReceivedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// StoreEvents is a parsable slice of StoreEvent.
type StoreEvents []*StoreEvent
