// Code generated by ent, DO NOT EDIT.

package ent

import (
	"adora-test/ent/predicate"
	"adora-test/ent/storeevent"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StoreEventDelete is the builder for deleting a StoreEvent entity.
type StoreEventDelete struct {
	config
	hooks    []Hook
	mutation *StoreEventMutation
}

// Where appends a list predicates to the StoreEventDelete builder.
func (_d *StoreEventDelete) Where(ps ...predicate.StoreEvent) *StoreEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *StoreEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StoreEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *StoreEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(storeevent.Table, sqlgraph.NewFieldSpec(storeevent.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// StoreEventDeleteOne is the builder for deleting a single StoreEvent entity.
type StoreEventDeleteOne struct {
	_d *StoreEventDelete
}

// Where appends a list predicates to the StoreEventDelete builder.
func (_d *StoreEventDeleteOne) Where(ps ...predicate.StoreEvent) *StoreEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *StoreEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{storeevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StoreEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
